name: laravel
language: php
paradigm: mvc
fileExtension: .php
skeleton:
  - template: skeleton/composer.json.hbs
    output: composer.json
  - template: skeleton/env.hbs
    output: .env
  - template: skeleton/Controller.php.hbs
    output: app/Http/Controllers/Controller.php
  - template: skeleton/api.php.hbs
    output: routes/api.php
  - template: skeleton/Dockerfile.hbs
    output: Dockerfile
  - template: skeleton/docker-compose.yml.hbs
    output: docker-compose.yml
  - template: skeleton/migration.php.hbs
    output: database/migrations/0001_01_01_000000_create_tables.php
entityTemplates:
  - template: entity/Model.php.hbs
    output: app/Models/{{className}}.php
  - template: entity/StoreRequest.php.hbs
    output: app/Http/Requests/Store{{className}}Request.php
  - template: entity/UpdateRequest.php.hbs
    output: app/Http/Requests/Update{{className}}Request.php
  - template: entity/Resource.php.hbs
    output: app/Http/Resources/{{className}}Resource.php
  - template: entity/Controller.php.hbs
    output: app/Http/Controllers/Api/{{className}}Controller.php
  - template: entity/ModelTest.php.hbs
    output: tests/Unit/Models/{{className}}Test.php
    test: true
