import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { resolve } from 'node:path';
import Handlebars from 'handlebars';
import { TemplateEngine, registerAllHelpers } from './index.js';
import { type CoderConfig } from '../config/index.js';
import { type TableSchema } from '../schema/index.js';

describe('Handlebars Template Engine (T5)', () => {
  describe('Helper Registrations', () => {
    const hbs = Handlebars;
    beforeEach(() => {
      registerAllHelpers(hbs);
    });

    it('should format className helper correctly', () => {
      const template = hbs.compile('{{className "sys_user_role"}}');
      expect(template({})).toBe('SysUserRole');
    });

    it('should format propertyName helper correctly with default and custom lang', () => {
      const templateDefault = hbs.compile('{{propertyName "created_at"}}');
      expect(templateDefault({})).toBe('createdAt');

      const templateGo = hbs.compile('{{propertyName "created_at" lang="go"}}');
      expect(templateGo({})).toBe('CreatedAt');

      const templatePython = hbs.compile('{{propertyName "created_at" lang="python"}}');
      expect(templatePython({})).toBe('created_at');
    });

    it('should format indent helper correctly', () => {
      const templateDefault = hbs.compile('{{indent}}');
      expect(templateDefault({})).toBe('    ');

      const templateDouble = hbs.compile('{{indent 2}}');
      expect(templateDouble({})).toBe('        ');
    });

    it('should format mapType helper correctly', () => {
      const templateDefault = hbs.compile('{{mapType "bigint"}}');
      expect(templateDefault({})).toBe('Long');

      const templateTS = hbs.compile('{{mapType "bigint" lang="typescript"}}');
      expect(templateTS({})).toBe('number');
    });

    it('should format pluralize helper correctly', () => {
      const template = hbs.compile('{{pluralize "category"}}');
      expect(template({})).toBe('categories');
    });

    it('should handle logical helpers', () => {
      expect(hbs.compile('{{#if (eq 1 1)}}yes{{else}}no{{/if}}')({})).toBe('yes');
      expect(hbs.compile('{{#if (eq 1 2)}}yes{{else}}no{{/if}}')({})).toBe('no');
      expect(hbs.compile('{{#if (ne 1 2)}}yes{{else}}no{{/if}}')({})).toBe('yes');
      expect(hbs.compile('{{#if (and true true)}}yes{{else}}no{{/if}}')({})).toBe('yes');
      expect(hbs.compile('{{#if (and true false)}}yes{{else}}no{{/if}}')({})).toBe('no');
      expect(hbs.compile('{{#if (or true false)}}yes{{else}}no{{/if}}')({})).toBe('yes');
      expect(hbs.compile('{{#if (not false)}}yes{{else}}no{{/if}}')({})).toBe('yes');
    });
  });

  describe('Plugin Loading and Rendering Pipelines', () => {
    const pluginDir = resolve(process.cwd(), 'test-plugin-dir');

    beforeEach(() => {
      // 创建测试用的临时插件目录
      if (existsSync(pluginDir)) {
        rmSync(pluginDir, { recursive: true, force: true });
      }
      mkdirSync(pluginDir, { recursive: true });
      mkdirSync(resolve(pluginDir, 'skeleton'), { recursive: true });
      mkdirSync(resolve(pluginDir, 'entity'), { recursive: true });
      mkdirSync(resolve(pluginDir, 'partials'), { recursive: true });

      // 写入 plugin.yml
      const pluginYml = `
name: test-plugin
language: typescript
paradigm: lightweight
fileExtension: .ts
skeleton:
  - template: skeleton/main.ts.hbs
    output: src/{{projectClassName}}Main.ts
entityTemplates:
  - template: entity/model.ts.hbs
    output: src/models/{{kebabCase tableName}}.ts
`;
      writeFileSync(resolve(pluginDir, 'plugin.yml'), pluginYml, 'utf-8');

      // 写入 skeleton/main.ts.hbs
      writeFileSync(
        resolve(pluginDir, 'skeleton/main.ts.hbs'),
        'console.log("Welcome to {{projectClassName}}!");',
        'utf-8',
      );

      // 写入 entity/model.ts.hbs
      const modelHbs = `
export class {{className tableName}} {
{{#each columns}}
    {{propertyName name lang="typescript"}}: {{mapType sqlType lang="typescript"}};
{{/each}}
}
`;
      writeFileSync(resolve(pluginDir, 'entity/model.ts.hbs'), modelHbs, 'utf-8');

      // 写入 partials/header.hbs
      writeFileSync(
        resolve(pluginDir, 'partials/header.hbs'),
        '// Generated by Coder Engine\n',
        'utf-8',
      );
    });

    afterEach(() => {
      if (existsSync(pluginDir)) {
        rmSync(pluginDir, { recursive: true, force: true });
      }
    });

    it('should load plugin metadata and register partials', () => {
      const engine = new TemplateEngine();
      engine.loadPlugin(pluginDir);

      const metadata = engine.getPluginMetadata();
      expect(metadata.name).toBe('test-plugin');
      expect(metadata.language).toBe('typescript');
      expect(metadata.skeleton?.length).toBe(1);
      expect(metadata.entityTemplates?.length).toBe(1);
    });

    it('should render skeleton files correctly', () => {
      const engine = new TemplateEngine();
      engine.loadPlugin(pluginDir);

      const config: CoderConfig = {
        datasource: { type: 'ddl', input: 'schema.sql' },
        target: {
          framework: 'nestjs',
          output: './out',
          package: 'com.example.superapp',
        },
        tables: { include: [], exclude: [] },
        features: { swagger: true, unitTest: true, pagination: true, auditFields: true },
        extensions: {},
      };

      const outputs = engine.renderSkeleton(config);
      expect(outputs.length).toBe(1);
      expect(outputs[0].outputPath).toBe('src/SuperappMain.ts'); // Derived from package com.example.superapp -> Superapp -> SuperappMain.ts
      expect(outputs[0].content).toBe('console.log("Welcome to Superapp!");');
    });

    it('should render entity files correctly', () => {
      const engine = new TemplateEngine();
      engine.loadPlugin(pluginDir);

      const config: CoderConfig = {
        datasource: { type: 'ddl', input: 'schema.sql' },
        target: {
          framework: 'nestjs',
          output: './out',
          package: 'com.example.superapp',
        },
        tables: { include: [], exclude: [] },
        features: { swagger: true, unitTest: true, pagination: true, auditFields: true },
        extensions: {},
      };

      const table: TableSchema = {
        name: 'sys_user',
        className: 'SysUser',
        comment: '系统用户表',
        primaryKey: ['user_id'],
        indexes: [],
        foreignKeys: [],
        columns: [
          {
            name: 'user_id',
            propertyName: 'userId',
            sqlType: 'bigint',
            rawType: 'bigint',
            nullable: false,
            isPrimaryKey: true,
            isAutoIncrement: true,
            javaType: 'Long',
            goType: 'int64',
            pythonType: 'int',
            phpType: 'int',
            tsType: 'number',
          },
          {
            name: 'username',
            propertyName: 'username',
            sqlType: 'varchar',
            rawType: 'varchar(50)',
            nullable: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            javaType: 'String',
            goType: 'string',
            pythonType: 'str',
            phpType: 'string',
            tsType: 'string',
          },
        ],
      };

      const outputs = engine.renderEntity(table, config);
      expect(outputs.length).toBe(1);
      expect(outputs[0].outputPath).toBe('src/models/sys-user.ts'); // derived from {{kebabCase tableName}} -> sys-user.ts
      expect(outputs[0].content).toContain('export class SysUser {');
      expect(outputs[0].content).toContain('userId: number;');
      expect(outputs[0].content).toContain('username: string;');
    });
  });
});
