name: fastapi
language: python
paradigm: lightweight
fileExtension: .py
skeleton:
  - template: skeleton/requirements.txt.hbs
    output: requirements.txt
  - template: skeleton/database.py.hbs
    output: database.py
  - template: skeleton/main.py.hbs
    output: main.py
  - template: skeleton/Dockerfile.hbs
    output: Dockerfile
  - template: skeleton/docker-compose.yml.hbs
    output: docker-compose.yml
  - template: skeleton/alembic.ini.hbs
    output: alembic.ini
entityTemplates:
  - template: entity/model.py.hbs
    output: models/{{snakeCase tableName}}.py
  - template: entity/schema.py.hbs
    output: schemas/{{snakeCase tableName}}.py
  - template: entity/crud.py.hbs
    output: crud/{{snakeCase tableName}}.py
  - template: entity/router.py.hbs
    output: routers/{{snakeCase tableName}}.py
  - template: entity/test_model.py.hbs
    output: tests/test_{{snakeCase tableName}}.py
    test: true
